server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=db_log
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update

logging:
  file:
    name: medical.log
